// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/db/ent/account"
	"server/db/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescUsername is the schema descriptor for username field.
	accountDescUsername := accountFields[1].Descriptor()
	// account.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	account.UsernameValidator = accountDescUsername.Validators[0].(func(string) error)
	// accountDescPassword is the schema descriptor for password field.
	accountDescPassword := accountFields[2].Descriptor()
	// account.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	account.PasswordValidator = accountDescPassword.Validators[0].(func(string) error)
	// accountDescSalt is the schema descriptor for salt field.
	accountDescSalt := accountFields[3].Descriptor()
	// account.SaltValidator is a validator for the "salt" field. It is called by the builders before save.
	account.SaltValidator = accountDescSalt.Validators[0].(func(string) error)
}
